### ISSUE TITLE
Google spreadsheet problem

### ISSUE THREAD

**Issue by swarzynski** [brandonrobertz/rescue-me#1]
Hi Brandon! First, thank you for great work. I like concept of rescue-me.

I have problem with google spreadsheet access. I cloned your repository locally - index.html work fine - app conects with your public accessible spreadsheet. But when I change URL variable with my key (from url [https://docs.google.com/spreadsheets/d/1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc](https://docs.google.com/spreadsheets/d/1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc) ) I get the error in the JS console, and page is not loaded:
`XMLHttpRequest cannot load https://www.google.com/accounts/ServiceLogin?service=wise&passive=1209600&c…TKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc/public/basic?alt%3Djson&ltmpl=sheets. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

What is the cause? Thank you for your help.

**Comment by brandonrobertz** [comment]
You're using the wrong document link. What you want to get is the link you receive when you publish the document non-protected. Note that your link is google.com and my link is docs.google.com. The link you're looking for will have the same format:

```
    https://docs.google.com/spreadsheets/d/TOKEN
```

**Comment by swarzynski** [comment]
Thank you for your answer.
I understand but I am using link (key from it) which I wrote in my first post:
https://docs.google.com/spreadsheets/d/1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc
This file is on my google account, it is exactly the same as yours (https://docs.google.com/spreadsheets/d/1y-kJ2lehFeMEn4avPAzf1b7RfsYTKL19fsznK8qaP_w) and it is in the same format as you stated above.

Only change I made in your code is changing:
`var URL = "1y-kJ2lehFeMEn4avPAzf1b7RfsYTKL19fsznK8qaP_w";`
to
`var URL = "1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc";`
in app.js
Your key is working, mine is not.

**Comment by brandonrobertz** [comment]
Okay I figured out the problem. Google Spreadsheets changed the way their servers work since I published my spreadsheet. What you need to do is go to `"File -> Publish to the Web..."` get that link and then insert it into URL. Full instructions are in the [README](https://github.com/brandonrobertz/rescue-me).

You should pull as I've updated the code. Let me know if this works for you.

**Comment by brandonrobertz** [comment]
@swarzynski did that fix the issue? closing if I don't hear back.

**Comment by swarzynski** [comment]
Hi Brandon, yes - thank you.
This works:
`var URL = "1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc";`
But this - don't:
`var URL = "https://docs.google.com/spreadsheets/d/1L1e59oTKBBO2M7eZ6rgD8UDFDxFBjTrKpHwB2gg7zmc";`
so maybe README update is necessary.

**Comment by brandonrobertz** [comment]
I updated the README, I had the old link in there still. Sounds like that "Publish to the Web" step was the missing link. Closing.
